// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parqueadero_Back.Database;

#nullable disable

namespace Parqueadero_Back.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106002946_CreacionDeTablaTransaccion")]
    partial class CreacionDeTablaTransaccion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parqueadero_Back.Models.Cupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cupo", t =>
                        {
                            t.HasCheckConstraint("CH_Cupo_EstadoDescripcion", "[EstadoDescripcion] IN ('Reservado', 'Ocupado', 'Disponible')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        },
                        new
                        {
                            Id = 2,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        },
                        new
                        {
                            Id = 4,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 5,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 6,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 7,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        },
                        new
                        {
                            Id = 8,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 9,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 10,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 11,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        },
                        new
                        {
                            Id = 12,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        },
                        new
                        {
                            Id = 13,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 14,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 15,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 16,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 17,
                            Estado = true,
                            EstadoDescripcion = "Reservado"
                        },
                        new
                        {
                            Id = 18,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 19,
                            Estado = false,
                            EstadoDescripcion = "Disponible"
                        },
                        new
                        {
                            Id = 20,
                            Estado = true,
                            EstadoDescripcion = "Ocupado"
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetodoPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tarjeta"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Transferencia"
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Costo")
                        .HasColumnType("float");

                    b.Property<int>("CupoId")
                        .HasColumnType("int");

                    b.Property<double?>("Duracion")
                        .HasColumnType("float");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngresoEstipulada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngresoReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CupoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Reserva", t =>
                        {
                            t.HasCheckConstraint("CK_Reserva_EstadoDescripcion", "[EstadoDescripcion] IN ('Activa', 'Finalizada', 'Cancelada')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CupoId = 1,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CupoId = 2,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 2
                        },
                        new
                        {
                            Id = 3,
                            CupoId = 3,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Costo = 96000.0,
                            CupoId = 4,
                            Duracion = 24.0,
                            Estado = true,
                            EstadoDescripcion = "Finalizada",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 6
                        },
                        new
                        {
                            Id = 5,
                            CupoId = 11,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 14
                        },
                        new
                        {
                            Id = 6,
                            CupoId = 18,
                            Estado = true,
                            EstadoDescripcion = "Cancelada",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 8
                        },
                        new
                        {
                            Id = 7,
                            Costo = 168000.0,
                            CupoId = 9,
                            Duracion = 48.0,
                            Estado = true,
                            EstadoDescripcion = "Finalizada",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 5
                        },
                        new
                        {
                            Id = 8,
                            CupoId = 20,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 16
                        },
                        new
                        {
                            Id = 9,
                            Costo = 336000.0,
                            CupoId = 13,
                            Duracion = 96.0,
                            Estado = true,
                            EstadoDescripcion = "Finalizada",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 11
                        },
                        new
                        {
                            Id = 10,
                            CupoId = 7,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 3
                        },
                        new
                        {
                            Id = 11,
                            CupoId = 17,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 9
                        },
                        new
                        {
                            Id = 12,
                            Costo = 96000.0,
                            CupoId = 15,
                            Duracion = 24.0,
                            Estado = true,
                            EstadoDescripcion = "Finalizada",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 10
                        },
                        new
                        {
                            Id = 13,
                            CupoId = 12,
                            Estado = true,
                            EstadoDescripcion = "Activa",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 4
                        },
                        new
                        {
                            Id = 14,
                            Costo = 180000.0,
                            CupoId = 19,
                            Duracion = 24.0,
                            Estado = true,
                            EstadoDescripcion = "Finalizada",
                            FechaIngresoEstipulada = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaIngresoReal = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculoId = 15
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            NombreRol = "Operador"
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Soporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Soporte");
                });

            modelBuilder.Entity("Parqueadero_Back.Models.TipoTransaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoTransaccion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ingreso"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Egreso"
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransaccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("TipoTransaccionId");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificadorUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "Ow4CnX0NoSHlhq96QYGPFQ==",
                            IdentificadorUsuario = "CamiloAPerezP",
                            NombreCompleto = "Camilo Andres Perez Parra",
                            RolId = 2
                        },
                        new
                        {
                            Id = 2,
                            Contrasena = "eSuwoPwEaN2wXV/NfQt/lA==",
                            IdentificadorUsuario = "JhoanaECifuentes",
                            NombreCompleto = "Jhoana Estefania Cifuentes",
                            RolId = 2
                        },
                        new
                        {
                            Id = 3,
                            Contrasena = "UsPN3lexcl9LyHlIHuw6ew==",
                            IdentificadorUsuario = "NelsonAMunozS",
                            NombreCompleto = "Nelson Andres Muñoz Salinas",
                            RolId = 1
                        },
                        new
                        {
                            Id = 4,
                            Contrasena = "ouj96EN+PovtRy940zJAIA==",
                            IdentificadorUsuario = "SilenidSSarmiento",
                            NombreCompleto = "Silenid Salinas Sarmiento",
                            RolId = 2
                        },
                        new
                        {
                            Id = 5,
                            Contrasena = "FhqsQlGPwXDJgjpPBJ9mHA==",
                            IdentificadorUsuario = "DanielaFRamirezO",
                            NombreCompleto = "Daniela Fernanda Ramirez Ortiz",
                            RolId = 2
                        },
                        new
                        {
                            Id = 6,
                            Contrasena = "S7EAxI4LweQlUKawN7+yMw==",
                            IdentificadorUsuario = "CarlosETorresM",
                            NombreCompleto = "Carlos Eduardo Torres Medina",
                            RolId = 2
                        },
                        new
                        {
                            Id = 7,
                            Contrasena = "BqcM1SAYio4g4wx94cGD8A==",
                            IdentificadorUsuario = "LauraVPinedaG",
                            NombreCompleto = "Laura Vanessa Pineda Gomez",
                            RolId = 2
                        },
                        new
                        {
                            Id = 8,
                            Contrasena = "Ura9j/soWm9XtY6aZeh+mg==",
                            IdentificadorUsuario = "JuanCRodriguezS",
                            NombreCompleto = "Juan Camilo Rodriguez Silva",
                            RolId = 2
                        },
                        new
                        {
                            Id = 9,
                            Contrasena = "/wIwgBJC+x66mtAn9Rtqcg==",
                            IdentificadorUsuario = "ValentinaNRojasD",
                            NombreCompleto = "Valentina Nicole Rojas Diaz",
                            RolId = 2
                        },
                        new
                        {
                            Id = 10,
                            Contrasena = "qRPJ1XEsRadus8k762LyPw==",
                            IdentificadorUsuario = "DavidAAcostaP",
                            NombreCompleto = "David Alejandro Acosta Peña",
                            RolId = 2
                        },
                        new
                        {
                            Id = 11,
                            Contrasena = "BFMmtRWsaydyTpPSN+iRHg==",
                            IdentificadorUsuario = "MarianaSCastilloL",
                            NombreCompleto = "Mariana Sofía Castillo Lara",
                            RolId = 2
                        },
                        new
                        {
                            Id = 12,
                            Contrasena = "iadC0NZMHKxjZX5ekTEOXw==",
                            IdentificadorUsuario = "SebastianAVegaM",
                            NombreCompleto = "Sebastian Andres Vega Muñoz",
                            RolId = 2
                        },
                        new
                        {
                            Id = 13,
                            Contrasena = "zp933pVbM1vUX/UIE+jCEg==",
                            IdentificadorUsuario = "NicolasAHerreraC",
                            NombreCompleto = "Nicolas Adrian Herrera Cruz",
                            RolId = 2
                        },
                        new
                        {
                            Id = 14,
                            Contrasena = "ojD4mP/JBovXB46YzCEIlg==",
                            IdentificadorUsuario = "PaulaAMendozaR",
                            NombreCompleto = "Paula Andrea Mendoza Ruiz",
                            RolId = 2
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cilindraje")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vehiculo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cilindraje = 125,
                            Placa = "SBX-78F",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cilindraje = 200,
                            Placa = "ERF-23G",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cilindraje = 400,
                            Placa = "FGH-66H",
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 4,
                            Cilindraje = 125,
                            Placa = "AAE-34F",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cilindraje = 200,
                            Placa = "GJK-45B",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 6,
                            Cilindraje = 250,
                            Placa = "FCX-66B",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cilindraje = 125,
                            Placa = "HPL-90C",
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 8,
                            Cilindraje = 250,
                            Placa = "KSD-81A",
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 9,
                            Cilindraje = 200,
                            Placa = "ZXC-22D",
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 10,
                            Cilindraje = 400,
                            Placa = "RTV-14F",
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 11,
                            Cilindraje = 125,
                            Placa = "POE-76B",
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 12,
                            Cilindraje = 250,
                            Placa = "BMN-99E",
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 13,
                            Cilindraje = 200,
                            Placa = "LMQ-45C",
                            UsuarioId = 10
                        },
                        new
                        {
                            Id = 14,
                            Cilindraje = 400,
                            Placa = "QWE-33H",
                            UsuarioId = 11
                        },
                        new
                        {
                            Id = 15,
                            Cilindraje = 125,
                            Placa = "PLM-50G",
                            UsuarioId = 11
                        },
                        new
                        {
                            Id = 16,
                            Cilindraje = 250,
                            Placa = "VBN-07K",
                            UsuarioId = 13
                        });
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Reserva", b =>
                {
                    b.HasOne("Parqueadero_Back.Models.Cupo", "Cupo")
                        .WithMany()
                        .HasForeignKey("CupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parqueadero_Back.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Soporte", b =>
                {
                    b.HasOne("Parqueadero_Back.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Transaccion", b =>
                {
                    b.HasOne("Parqueadero_Back.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parqueadero_Back.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parqueadero_Back.Models.TipoTransaccion", "TipoTransaccion")
                        .WithMany()
                        .HasForeignKey("TipoTransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Reserva");

                    b.Navigation("TipoTransaccion");
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Usuario", b =>
                {
                    b.HasOne("Parqueadero_Back.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Parqueadero_Back.Models.Vehiculo", b =>
                {
                    b.HasOne("Parqueadero_Back.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
